Bpi\ApiBundle\Domain\Aggregate\Node:
#  db: documents
  repositoryClass: Bpi\ApiBundle\Domain\Repository\NodeRepository
  collection: Node
  fields:
    id:
      id: true

    ctime:
      type: date
      index: true
      order: desc

    mtime:
      type: date

    syndications:
      type: int

    deleted:
       type: boolean

    author:
      embedded: true
      type: one
      strategy: pushAll
      targetDocument: Bpi\ApiBundle\Domain\Entity\Author

    profile:
      embedded: true
      type: one
      strategy: pushAll
      targetDocument: Bpi\ApiBundle\Domain\Entity\Profile

    resource:
      embedded: true
      type: one
      strategy: pushAll
      targetDocument: Bpi\ApiBundle\Domain\Entity\Resource

    params:
      embedded: true
      type: one
      strategy: pushAll
      targetDocument: Bpi\ApiBundle\Domain\Aggregate\Params

    category:
      reference: true
      type: one
      targetDocument: Bpi\ApiBundle\Domain\Entity\Category

    audience:
      reference: true
      type: one
      targetDocument: Bpi\ApiBundle\Domain\Entity\Audience

    assets:
      embedded: true
      type: one
      strategy: pushAll
      targetDocument: Bpi\ApiBundle\Domain\Aggregate\Assets