Bpi\ApiBundle\Domain\Aggregate\Node:
  collection: Node
  repositoryClass: Bpi\ApiBundle\Domain\Repository\NodeRepository

  fields:
    id:
      id: true

    ctime:
      type: date
      index: true
      order: desc

    mtime:
      type: date

    syndications:
      type: int

    path:
      type: string

    level:
      type: int

    parent:
      reference: true
      type: one
      targetDocument: Bpi\ApiBundle\Domain\Aggregate\Node
      strategy: set
      cascade: all

    lock_time:
      type: date

    deleted:
       type: boolean

    author:
      embedded: true
      type: one
      strategy: set
      targetDocument: Bpi\ApiBundle\Domain\Entity\Author

    profile:
      embedded: true
      type: one
      strategy: set
      targetDocument: Bpi\ApiBundle\Domain\Entity\Profile

    resource:
      embedded: true
      type: one
      strategy: set
      targetDocument: Bpi\ApiBundle\Domain\Entity\Resource

    params:
      embedded: true
      type: one
      strategy: set
      targetDocument: Bpi\ApiBundle\Domain\Aggregate\Params

    category:
      reference: true
      type: one
      targetDocument: Bpi\ApiBundle\Domain\Entity\Category

    audience:
      reference: true
      type: one
      targetDocument: Bpi\ApiBundle\Domain\Entity\Audience

    tags:
      reference: true
      type: many
      targetDocument: Bpi\ApiBundle\Domain\Entity\Tag
      cascade: all

    assets:
      embedded: true
      type: one
      strategy: set
      targetDocument: Bpi\ApiBundle\Domain\Aggregate\Assets
