Bpi\ApiBundle\Domain\Entity\User:
  repositoryClass: Bpi\ApiBundle\Domain\Repository\UserRepository
  collection: User
  type: document

  fields:
    id:
      id: true
    name:
      type: string

  referenceOne:
    userAgency:
      targetDocument: Bpi\ApiBundle\Aggregate\Agency
