Bpi\ApiBundle\Domain\Entity\File:
  collection: File
  repositoryClass: Bpi\ApiBundle\Domain\Repository\FileRepository
  type: embeddedDocument

  fields:
    path:
      type: string
    name:
      type: string
    title:
      type: string
    alt:
      type: string
    extension:
      type: string
    external:
      type: string
    type:
      type: string
    width:
      type: int
    height:
      type: int
