Bpi\ApiBundle\Domain\Entity\Resource:
  type: embeddedDocument
  fields:
    title:
      type: string
    body:
      type: string
    teaser:
      type: string
    ctime:
      type: date
    type:
      type: string
    hash:
      type: string
    copyleft:
      embedded: true
      type: one
      strategy: set
      targetDocument: Bpi\ApiBundle\Domain\ValueObject\Copyleft
    url:
      type: string
    data:
      type: string
  embedMany:
    materials:
      targetDocument: Bpi\ApiBundle\Domain\ValueObject\Material
  lifecycleCallbacks:
    postLoad: [ wakeup ]
