imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    api_version: 3.0

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# JMSSerializerBundle has obsolete dependency on doctrine service
doctrine:
    orm:
        auto_mapping: false
    dbal:
        default_connection: default

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            # server: mongodb://%mongodb_user%:%mongodb_pass%@localhost:27017/%mongodb_db%
            options: {}
    default_database: %mongodb_db%
    document_managers:
        default:
            mappings:
                BpiApiBundle:
                    type: yml
                    prefix: Bpi\ApiBundle\Domain
#                gedmo_tree:
#                    type: yml
#                    prefix: Gedmo\Tree\Document
#                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Document"
#                    alias: GedmoTree # this one is optional and will default to the name set for the mapping
#                    is_bundle: false

mongo_db_migrations:
    collection_name: "migration_versions"
    database_name: "%mongodb_db%"
    dir_name: "%kernel.root_dir%/../src/Bpi/ApiBundle/Resources/config/Migrations/MongoDB"
    script_dir_name: "%kernel.root_dir%/scripts"
    name: "Bpi API bundle MongoDB Migrations"
    namespace: "Bpi\\ApiBundle\\Migrations\\MongoDB"

stof_doctrine_extensions:
    default_locale: en_US
    mongodb:
        default:
            tree: true

nelmio_api_doc: ~

sensio_framework_extra:
    view:    { annotations: true }
    router:  { annotations: true }

fos_rest:
    exception:
        enabled: true
    service:
      view_handler: bpi.apibundle.rest.view_handler
    routing_loader:
        default_format: bpi
    view:
        view_response_listener: true
        formats:
              json: true
              xml: true
              bpi: true
              rss: false
              gif: true
              jpg: true
              png: true
              html: true
        templating_formats:
            html: true
        mime_types:
            bpi:
               - 'application/vnd.bpi.api+xml'
            json:
               - 'application/json'
            xml:
               - 'application/xml'

jms_serializer:
    metadata:
        debug: "%kernel.debug%"
        auto_detection: true

knp_gaufrette:
    adapters:
        attachment:
            gridfs:
                mongogridfs_id: bpi.gridfs
    filesystems:
        assets:
            adapter: attachment
swiftmailer:
    transport: %mailer_transport%
    host: %mailer_host%
    username: %mailer_user%
    password: %mailer_password%
