parameters:
    secret: 5$Z[$}Wm}g@Qc@;w@>l3HqWj1
    locale: en
    mongodb_db: bpi
    swiftmailer:

    mailer_transport: smtp
    mailer_encription: ssl
    mailer_auth_mode: login
    mailer_host: smtp.gmail.com
    mailer_user: makcumm@gmail.com
    mailer_password: compaq_nc6120
