parameters:
    unit_test_domain: bpiservice.dev
    secret: 5$Z[$}Wm}g@Qc@;w@>l3HqWj1
    locale: en
    mongodb_db: bpi_prod
    swiftmailer: ~

    mailer_transport: gmail
    mailer_host: ~
    mailer_user: some@email.com
    mailer_password: email_password
