bpi_admin:
    resource: "@BpiAdminBundle/Controller/"
    prefix: /admin
    type: annotation

bpi_api:
    resource: "@BpiApiBundle/Controller/"
    type: rest

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

logout:
    path: /admin/logout
