bpi_admin:
    resource: "@BpiAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

bpi_api:
    resource: Bpi\ApiBundle\Controller\RestController
    type: rest

bpi_api_channels:
    resource: Bpi\ApiBundle\Controller\ChannelController
    type: rest
    prefix: /channel

bpi_api_users:
    resource: Bpi\ApiBundle\Controller\UserController
    type: rest
    prefix: /user

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

logout:
    pattern: /admin/logout
