bpi_admin:
    resource: "@BpiAdminBundle/Controller/"
    prefix: /admin
    type: annotation

bpi_api:
    resource: "@BpiApiBundle/Controller/"
    type: rest

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

logout:
    path: /admin/logout
