security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        agencies:
            id: bpi.pk.security.user_provider
        admins:
            memory:
                users:
                    admin:
                        password: admin
                        roles: ROLE_ADMIN
                    sa:
                        password: sa
                        roles: ROLE_SUPER_ADMIN

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        documentation:
            pattern:  ^/.+\.html$
            security: false

        schema:
            pattern: ^/schema.*
            security: false

        mainpage:
            pattern: ^/$
            security: false

        admin:
            pattern: ^/admin
            anonymous: ~
            stateless: true
            http_basic:
                realm: "BPI Admin"
                provider: admins
            logout:
                path:   /admin/logout
                target: /

        assets:
            pattern: ^/asset/
            security: false

        api:
            pattern:   ^/
            pk:      true
            stateless: true

    access_control:
        - { path: ^/admin/notification, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
